-- =============================================================================
-- FAZ 3a / 01 — Taksonomi: service_roles tablosu, service_categories genislemesi, aynalama, dolum
--
-- Kaynak: docs/architecture/03-taksonomi.md ("Goc yontemi", bolum 1-2), 04-goc-plani.md FAZ 3 (18-21).
-- Plan: docs/envanter/12-faz3a-service-roles.md
--
-- NE YAPAR (yalniz ekleme; FK'ler, sayfalar, bes yapilandirma dosyasi degismez):
--   1) service_categories + layer ('legacy_role' | 'category') + parent_id. Mevcut 23 satir 'legacy_role':
--      bugun bunlar rol duzeyindedir (fotografci, dj, sunucu). Ust servis kategorisi satirlari (6-8 grup,
--      3b, ekip eslemesi) 'category' katmaniyla eklenir.
--   2) service_roles (integer pk — taksonomi tablolari integer, 01 anahtar kurali): eslestirmenin temel
--      birimi. slug = service_categories.slug BIREBIR (bes yapilandirma dosyasi slug ile anahtarli;
--      slug degisirse ikonlar, icerik, filtre, brief kirilir). legacy_category_id eski kimligi tasir;
--      services.category_id, listings.category_id, quote_requests.category_id, profiles.primary_category_id
--      dokunulmadan calisir. archetype: category-fields.ts'teki dort sabit arketipin KOLAYLIK KOPYASI
--      (kaynak TypeScript'te kalir, 03 bolum 2); dolumda slug'a gore doldurulur, eslesmeyen NULL kalir
--      (asama8 K5 sayar).
--   3) Aynalama: service_categories (layer = legacy_role) INSERT/UPDATE -> service_roles (legacy_category_id
--      anahtariyla upsert). Admin bugun yeni kategoriyi service_categories'e yazar (kategori talebi onayi);
--      rol satiri otomatik dogar. Hata eski akisi kesmez: organization_sync_log.
--   4) Dolum: mevcut satirlar service_roles'a kopyalanir (idempotan).
--
-- AD KARARI (18 Eylul, Guven): tablo `roles` DEGIL `service_roles`. Kod tabaninda "role" zaten iki kavram
--   (profiles.role, organization_memberships.role); ucuncusu ayni kelimeyle yasamaz. FK sutunlari `role_id`
--   kalir (provider_services.role_id, event_requirements.role_id).
--
-- YETKI: service_categories ile ayni — herkese okunur; INSERT/UPDATE yalniz admin (politika); DELETE yok.
--   Tablo GRANT'lari 09_platform_katmani varsayilanindan gelir; burada acikca yazilir.
--
-- Idempotan. Sapkali harf yok. Veri: yalniz bolum 5 (dolum) yazar, eski tabloyu degistirmez
--   (layer sutunu DEFAULT ile dolar).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1) service_categories genislemesi
-- -----------------------------------------------------------------------------
ALTER TABLE public.service_categories
  ADD COLUMN IF NOT EXISTS layer text NOT NULL DEFAULT 'legacy_role',
  ADD COLUMN IF NOT EXISTS parent_id integer REFERENCES public.service_categories(id) ON DELETE SET NULL;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'service_categories_layer_check') THEN
    ALTER TABLE public.service_categories
      ADD CONSTRAINT service_categories_layer_check CHECK (layer IN ('legacy_role', 'category'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'service_categories_parent_not_self') THEN
    ALTER TABLE public.service_categories
      ADD CONSTRAINT service_categories_parent_not_self CHECK (parent_id IS NULL OR parent_id <> id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS service_categories_layer_idx ON public.service_categories (layer);

-- -----------------------------------------------------------------------------
-- 2) service_roles
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.service_roles (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_category_id integer REFERENCES public.service_categories(id) ON DELETE SET NULL,  -- ust katman; 3b'de dolar
  slug                text NOT NULL,
  name_tr             text NOT NULL,
  emoji               text,
  archetype           text,                                   -- TS kopyasi; NULL = eslesmedi
  legacy_category_id  integer REFERENCES public.service_categories(id) ON DELETE SET NULL,
  sort_order          integer NOT NULL DEFAULT 0,
  is_active           boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT service_roles_slug_key UNIQUE (slug),
  CONSTRAINT service_roles_legacy_category_id_key UNIQUE (legacy_category_id),
  CONSTRAINT service_roles_slug_check CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  CONSTRAINT service_roles_archetype_check CHECK (archetype IS NULL OR archetype IN ('sahne', 'cast', 'produksiyon', 'uzmanlik')),
  -- 03 bolum 6: PostgREST or= dilbilgisinde yasak karakterler filtreye baglanabilecek her taksonomi degerinde yasak
  CONSTRAINT service_roles_name_tr_check CHECK (name_tr !~ '[,()"\\]')
);

CREATE INDEX IF NOT EXISTS service_roles_service_category_id_idx ON public.service_roles (service_category_id);
CREATE INDEX IF NOT EXISTS service_roles_active_sort_idx ON public.service_roles (is_active, sort_order);

DROP TRIGGER IF EXISTS on_service_roles_updated ON public.service_roles;
CREATE TRIGGER on_service_roles_updated BEFORE UPDATE ON public.service_roles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- -----------------------------------------------------------------------------
-- 3) Arketip kopyasi (kaynak: app/lib/category-fields.ts CATEGORY_PRESETS, 18 Eylul; 23 slug)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.service_role_archetype_for_slug(p_slug text)
RETURNS text
LANGUAGE sql IMMUTABLE
AS $$
  SELECT CASE p_slug
    WHEN 'dj' THEN 'sahne' WHEN 'muzisyen' THEN 'sahne' WHEN 'dansci' THEN 'sahne'
    WHEN 'stand-up-komedyen' THEN 'sahne' WHEN 'illuzyonist' THEN 'sahne' WHEN 'palyaco' THEN 'sahne'
    WHEN 'sunucu' THEN 'sahne' WHEN 'akrobat' THEN 'sahne'
    WHEN 'model' THEN 'cast' WHEN 'oyuncu' THEN 'cast' WHEN 'hostes' THEN 'cast'
    WHEN 'fotografci' THEN 'produksiyon' WHEN 'videograf' THEN 'produksiyon' WHEN 'ses-isik' THEN 'produksiyon'
    WHEN 'sac-makyaj-styling' THEN 'produksiyon' WHEN 'canli-yayin' THEN 'produksiyon' WHEN 'drone-pilotu' THEN 'produksiyon'
    WHEN 'tercuman' THEN 'uzmanlik' WHEN 'organizasyon' THEN 'uzmanlik' WHEN 'etkinlik-koordinatoru' THEN 'uzmanlik'
    WHEN 'konusmaci' THEN 'uzmanlik' WHEN 'influencer' THEN 'uzmanlik' WHEN 'karikaturist' THEN 'uzmanlik'
    ELSE NULL
  END
$$;

-- -----------------------------------------------------------------------------
-- 4) Aynalama: service_categories (legacy_role) -> service_roles
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_sync_category_to_service_role()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.layer <> 'legacy_role' THEN
    RETURN NEW;                 -- ust katman satirlari rol degildir
  END IF;

  BEGIN
    INSERT INTO public.service_roles (slug, name_tr, emoji, archetype, legacy_category_id, sort_order, is_active, created_at)
    VALUES (NEW.slug, NEW.name_tr, NEW.emoji, public.service_role_archetype_for_slug(NEW.slug), NEW.id,
            NEW.sort_order, NEW.is_active, COALESCE(NEW.created_at, now()))
    ON CONFLICT (legacy_category_id) DO UPDATE
      SET slug       = EXCLUDED.slug,
          name_tr    = EXCLUDED.name_tr,
          emoji      = EXCLUDED.emoji,
          archetype  = COALESCE(public.service_roles.archetype, EXCLUDED.archetype),  -- elle verilmis arketip korunur
          sort_order = EXCLUDED.sort_order,
          is_active  = EXCLUDED.is_active;
  EXCEPTION WHEN OTHERS THEN
    PERFORM public.log_org_sync_error(TG_NAME, TG_OP, NULL, 'service_categories id=' || NEW.id || ': ' || SQLERRM);
  END;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.fn_sync_category_to_service_role() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_faz3_sync_category_to_service_role ON public.service_categories;
CREATE TRIGGER trg_faz3_sync_category_to_service_role
  AFTER INSERT OR UPDATE OF slug, name_tr, emoji, sort_order, is_active, layer
  ON public.service_categories
  FOR EACH ROW EXECUTE FUNCTION public.fn_sync_category_to_service_role();

-- -----------------------------------------------------------------------------
-- 5) Dolum (idempotan): mevcut legacy_role satirlari -> service_roles
-- -----------------------------------------------------------------------------
INSERT INTO public.service_roles (slug, name_tr, emoji, archetype, legacy_category_id, sort_order, is_active, created_at)
SELECT sc.slug, sc.name_tr, sc.emoji, public.service_role_archetype_for_slug(sc.slug), sc.id,
       sc.sort_order, sc.is_active, COALESCE(sc.created_at, now())
  FROM public.service_categories sc
 WHERE sc.layer = 'legacy_role'
   AND NOT EXISTS (SELECT 1 FROM public.service_roles r WHERE r.legacy_category_id = sc.id)
 ORDER BY sc.sort_order, sc.id
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 6) Yetki + RLS (service_categories ile ayni desen)
-- -----------------------------------------------------------------------------
GRANT SELECT ON public.service_roles TO anon, authenticated;
GRANT INSERT, UPDATE ON public.service_roles TO authenticated;      -- RLS: yalniz admin
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.service_roles FROM anon, authenticated;
REVOKE INSERT, UPDATE ON public.service_roles FROM anon;
GRANT ALL ON public.service_roles TO service_role;

ALTER TABLE public.service_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS service_roles_read_all ON public.service_roles;
CREATE POLICY service_roles_read_all ON public.service_roles FOR SELECT USING (true);

DROP POLICY IF EXISTS service_roles_insert_admin ON public.service_roles;
CREATE POLICY service_roles_insert_admin ON public.service_roles FOR INSERT WITH CHECK (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS service_roles_update_admin ON public.service_roles;
CREATE POLICY service_roles_update_admin ON public.service_roles FOR UPDATE
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

COMMIT;
